version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Asia/Bangkok"
    open-pull-requests-limit: 10
    reviewers:
      - "Nutonspeed"
    assignees:
      - "Nutonspeed"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    # Group security updates together
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security-update"
      major-updates:
        patterns:
          - "*"
        update-types:
          - "version-update:semver-major"
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "version-update:semver-minor"
    # Allow both direct and indirect updates
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Ignore specific packages if needed
    ignore:
      - dependency-name: "eslint"
        versions: ["9.x"]
      - dependency-name: "typescript"
        versions: [">= 5.4.0"]
    # Enable security advisories
    labels:
      - "dependencies"
      - "security"
    milestone: 1

  # Enable updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Bangkok"
    open-pull-requests-limit: 5
    reviewers:
      - "Nutonspeed"
    assignees:
      - "Nutonspeed"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "ci/cd"