name: Build on Node 18 (manual)

on:
  workflow_dispatch: {}
  push:
    branches:
      - "chore/try-build-node18"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@8.6.0 --activate
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run build
        run: pnpm build
        env:
          # Set CI environment variables to prevent build failures
          CI: true
          SKIP_NODE_VERSION_CHECK: "1"
          NEXT_PUBLIC_SUPABASE_URL: "https://mock.supabase.co"
          NEXT_PUBLIC_SUPABASE_ANON_KEY: "mock_key"
          NEXT_PUBLIC_USE_SUPABASE: "false"
